FROM ros:humble

# Create a workspace
WORKDIR /ros2_humble_ws/src

# Copy the package(s) to the workspace
COPY ./packages/* $WORKDIR

# install ros package
RUN apt-get update && apt-get install -y \
      ros-${ROS_DISTRO}-demo-nodes-cpp \
      ros-${ROS_DISTRO}-demo-nodes-py && \
    rm -rf /var/lib/apt/lists/*

COPY ./ros2_dockerfile/init.sh /root/init.sh

RUN chmod +x /root/init.sh

CMD [ "/root/init.sh"]