version: '3'
services:
  ros2_humble:
    build:
      context: .
      dockerfile: ./ros2_dockerfile/Dockerfile.ros2
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"

  gazebo:
    build:
      context: ./gazebo_dockerfile
      dockerfile: Dockerfile.gazebo
    environment:
      DISPLAY: ${DISPLAY}
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "5001:5001"
